### ISSUE TITLE
FR: allow running jj actions without showing a pager

### ISSUE THREAD

**Issue by noahmayr** [noahmayr/vjj#3]
**Is your feature request related to a problem? Please describe.**
It breaks the flow when a pager is opened for every small action, since you first have to quit it before you can continue.

**Describe the solution you'd like**
Either or both of these solutions:
- Some way to run commands silently and just update the log
- Some way to run commands and show the output inside the main UI (either preview, prompt, etc.) with it disappearing once you start entering other commands

**Describe alternatives you've considered**
Only showing a pager with the output if the command fails

**Comment by ilyagr** [comment]
Ah, I was wondering why they didn't work for me. I have `less` configured to quit of there's less than a page of output via the LESS variable.

Not sure what the best solution here is I'm general, but at least now I know.

**Comment by noahmayr** [comment]
That should be fixed now on main by unsetting that less flag. There's also #6 which changes the behavior to show command output of simpler commands in the preview window instead of a pager for less interruptions in your workflow
